const T={
id:{navHome:"Beranda",navTaiwan:"Tentang Taiwan",navServices:"Layanan Kami",navProcess:"Proses",navContact:"Kontak",eyebrow:"JASA KONSULTASI STUDY DI TAIWAN",heroTitle:"Wujudkan Masa Depan Anak Anda di Taiwan",heroText:"Kami membantu orang tua dan calon mahasiswa dalam proses aplikasi ke universitas di Taiwan dengan mudah, jelas, dan profesional.",point1:"Pendampingan dari awal hingga diterima",point2:"Bantuan aplikasi ke universitas di Taiwan",point3:"Persiapan dokumen lengkap dan akurat",consultNow:"Konsultasi Sekarang",seeServices:"Lihat Layanan",b1t:"Universitas Berkualitas",b1x:"Akses ke berbagai universitas terbaik di Taiwan.",b2t:"Biaya Terjangkau",b2x:"Biaya kuliah dan hidup yang relatif terjangkau.",b3t:"Banyak Beasiswa",b3x:"Peluang beasiswa dari pemerintah dan universitas.",b4t:"Aman & Nyaman",b4x:"Lingkungan aman, transportasi mudah, dan fasilitas modern.",servicesLabel:"LAYANAN",servicesTitle:"Layanan Kami",s1t:"Pemilihan Universitas",s1x:"Membantu memilih universitas dan program studi yang sesuai.",s2t:"Bantuan Aplikasi",s2x:"Pendampingan proses aplikasi, pendaftaran online, dan deadline.",s3t:"Persiapan Dokumen",s3x:"Membantu menyiapkan dan mengecek dokumen agar lengkap dan benar.",s4t:"Review Aplikasi",s4x:"Pengecekan akhir untuk mengurangi kesalahan dan dokumen terlewat.",s5t:"Follow-up & Update",s5x:"Membantu memahami update dari universitas dan langkah berikutnya.",processLabel:"LANGKAH DEMI LANGKAH",processTitle:"Proses Kami",p1t:"Konsultasi Awal",p1x:"Diskusi kebutuhan dan tujuan studi.",p2t:"Pemilihan Universitas",p2x:"Rekomendasi universitas dan program.",p3t:"Persiapan Dokumen",p3x:"Menyiapkan semua dokumen yang diperlukan.",p4t:"Pengiriman Aplikasi",p4x:"Pendampingan pengiriman sesuai deadline.",p5t:"Penerimaan",p5x:"Membantu memahami hasil dan tahap berikutnya.",whyLabel:"KENAPA TAIWAN?",whyTitle:"Mengapa Study di Taiwan?",why1:"Pendidikan berkualitas internasional",why2:"Biaya kuliah dan hidup yang kompetitif",why3:"Peluang beasiswa untuk mahasiswa internasional",why4:"Lingkungan aman dan transportasi nyaman",why5:"Kesempatan belajar Bahasa Mandarin",parentLabel:"UNTUK ORANG TUA",parentTitle:"Informasi yang Jelas, Proses yang Terarah",parentText:"Keputusan kuliah di luar negeri adalah keputusan keluarga. Kami menjelaskan setiap tahap dengan bahasa yang mudah dipahami.",ctaLabel:"MULAI DARI SINI",ctaTitle:"Siap Memulai Perjalanan Studi di Taiwan?",ctaText:"Hubungi kami untuk membicarakan kebutuhan siswa dan pilihan universitas.",ctaButton:"Hubungi Kami",footerText:"Pendampingan aplikasi studi di Taiwan untuk mahasiswa internasional dan keluarga.",footerContact:"Kontak"},
en:{navHome:"Home",navTaiwan:"Why Taiwan",navServices:"Services",navProcess:"Process",navContact:"Contact",eyebrow:"TAIWAN STUDY CONSULTING",heroTitle:"Build Your Child’s Future in Taiwan",heroText:"We help parents and prospective students navigate Taiwan university applications with a clear, practical, and professional process.",point1:"Guidance from the first step to admission",point2:"Taiwan university application assistance",point3:"Accurate and complete document preparation",consultNow:"Book a Consultation",seeServices:"View Services",b1t:"Quality Universities",b1x:"Access to a wide range of universities in Taiwan.",b2t:"Affordable Costs",b2x:"Competitive tuition fees and living expenses.",b3t:"Scholarships",b3x:"Scholarship opportunities from government and universities.",b4t:"Safe & Convenient",b4x:"Safe environment, convenient transport, and modern facilities.",servicesLabel:"SERVICES",servicesTitle:"How We Help",s1t:"University Selection",s1x:"We help identify universities and programs suited to the student.",s2t:"Application Assistance",s2x:"Guidance with applications, online systems, and deadlines.",s3t:"Document Preparation",s3x:"We help prepare and review required documents.",s4t:"Application Review",s4x:"A final check for common mistakes and missing documents.",s5t:"Follow-up & Updates",s5x:"We help you understand university updates and next steps.",processLabel:"STEP BY STEP",processTitle:"Our Process",p1t:"Initial Consultation",p1x:"Discuss needs and study goals.",p2t:"University Selection",p2x:"Recommend suitable universities and programs.",p3t:"Document Preparation",p3x:"Prepare all required documents.",p4t:"Application Submission",p4x:"Support submission before each deadline.",p5t:"Admission",p5x:"Help you understand results and next steps.",whyLabel:"WHY TAIWAN?",whyTitle:"Why Study in Taiwan?",why1:"Internationally recognized education",why2:"Competitive tuition and living costs",why3:"Scholarships for international students",why4:"Safe environment and convenient transport",why5:"Opportunity to learn Mandarin",parentLabel:"FOR PARENTS",parentTitle:"Clear Information, Structured Process",parentText:"Studying abroad is a family decision. We explain every stage in clear language so parents understand the requirements, timeline, and progress.",ctaLabel:"START HERE",ctaTitle:"Ready to Begin the Taiwan Study Journey?",ctaText:"Contact us to discuss the student’s needs and available university options.",ctaButton:"Contact Us",footerText:"Taiwan university application support for international students and their families.",footerContact:"Contact"},
ko:{navHome:"홈",navTaiwan:"대만 유학",navServices:"서비스",navProcess:"진행 절차",navContact:"문의",eyebrow:"대만 유학 상담 서비스",heroTitle:"자녀의 미래를 대만에서 준비하세요",heroText:"학부모와 예비 유학생이 대만 대학 지원 과정을 보다 쉽고 명확하게 진행할 수 있도록 전문적으로 도와드립니다.",point1:"상담부터 합격까지 단계별 지원",point2:"대만 대학 지원 절차 안내",point3:"정확하고 완전한 서류 준비",consultNow:"상담 신청",seeServices:"서비스 보기",b1t:"우수한 대학",b1x:"대만의 다양한 우수 대학 선택 가능",b2t:"합리적인 비용",b2x:"비교적 합리적인 학비와 생활비",b3t:"다양한 장학금",b3x:"정부 및 대학 장학금 기회",b4t:"안전하고 편리함",b4x:"안전한 환경, 편리한 교통, 현대적인 시설",servicesLabel:"서비스",servicesTitle:"제공 서비스",s1t:"대학 선택",s1x:"학생에게 적합한 대학과 전공 선택을 돕습니다.",s2t:"지원 절차 안내",s2x:"온라인 지원과 일정 및 마감일을 안내합니다.",s3t:"서류 준비",s3x:"필수 서류를 정확하게 준비하고 검토합니다.",s4t:"지원서 검토",s4x:"제출 전 오류와 누락 여부를 확인합니다.",s5t:"후속 안내",s5x:"대학의 진행 상황과 다음 단계를 안내합니다.",processLabel:"단계별 안내",processTitle:"진행 절차",p1t:"초기 상담",p1x:"필요 사항과 유학 목표를 확인합니다.",p2t:"대학 선택",p2x:"적합한 대학과 전공을 추천합니다.",p3t:"서류 준비",p3x:"필요한 모든 서류를 준비합니다.",p4t:"지원서 제출",p4x:"각 대학 마감일에 맞춰 제출합니다.",p5t:"합격 결과",p5x:"결과와 이후 절차를 안내합니다.",whyLabel:"왜 대만인가요?",whyTitle:"대만 유학의 장점",why1:"국제적으로 인정받는 교육",why2:"합리적인 학비와 생활비",why3:"외국인 유학생 장학금 기회",why4:"안전한 생활 환경과 편리한 교통",why5:"중국어 학습 기회",parentLabel:"학부모를 위해",parentTitle:"명확한 정보와 체계적인 과정",parentText:"해외 유학은 가족 전체의 중요한 결정입니다. 요구 조건과 일정, 진행 상황을 쉽게 이해할 수 있도록 안내합니다.",ctaLabel:"지금 시작하세요",ctaTitle:"대만 유학을 준비하고 계신가요?",ctaText:"학생의 상황과 가능한 대학 선택에 대해 상담해 드립니다.",ctaButton:"문의하기",footerText:"국제 학생과 가족을 위한 대만 대학 지원 서비스",footerContact:"문의"}
};
function setLang(lang){
  const d=T[lang]||T.id;
  document.documentElement.lang=lang==="ko"?"ko":lang;
  document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(d[k])el.textContent=d[k]});
  document.querySelectorAll("[data-lang]").forEach(btn=>btn.classList.toggle("active",btn.dataset.lang===lang));
  localStorage.setItem("siteLang",lang);
}
document.querySelectorAll("[data-lang]").forEach(btn=>btn.addEventListener("click",()=>setLang(btn.dataset.lang)));
setLang(localStorage.getItem("siteLang")||"id");
